[project]
name = "break-notif"
description = "A tool to notify for breaks."
version = "0.0.1"
authors = [
	{name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]


[project.scripts]
bnotif = "break_notif.main:main"
