[project]
name = "renotify"
description = "A tool to notify for breaks."
readme = "README.md"
version = "0.1.0"
authors = [
    {name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]
dependencies = [
    "notify_py"
]


[project.scripts]
renotify = "renotify.main:runner"
