[project]
name = "break-notify"
description = "A tool to notify for breaks."
version = "0.1.0"
authors = [
    {name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]
dependencies = [
    "notify_py"
]


[project.scripts]
bnotify = "break_notif.main:runner"
